// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzxzbytlvdoabrdvomoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6eHpieXRsdmRvYWJyZHZvbW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzMzMDQsImV4cCI6MjA2ODk0OTMwNH0.TadNvf6hutGdd9Iqu6zXWUCGk_q5-nk6bH9S2ERwxJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});